version: '3.4'

networks:
  mercoranetwork:

volumes:
  sqlserver_data:

services:
  mercora_database:
    container_name: mercora_database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8001:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PAssWord**
      - MSSQL_PID=Express
    networks:
      - mercoranetwork
  mercora_cache:
    image: redis:latest
    container_name: mercora_cache
    restart: always
    ports:
      - 6379:6379
    networks:
      - mercoranetwork
  mercora:
    container_name: mercora
    image: ${DOCKER_REGISTRY-}mercoraproject
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: src/Presentation/BlazorEcommerce.Server/Dockerfile
    depends_on:
      - mercora_database
      - mercora_cache
    networks:
      - mercoranetwork 
    volumes:
      - sqlserver_data:/var/opt/mssql
